name:                tip
version:             0.1.0.0
github:              "fwcd/tip"
license:             BSD3
author:              "fwcd"
copyright:           "2020 fwcd"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/tip#readme>

dependencies:
- base >= 4.7 && < 5
- parsec >= 3.1 && < 4
- either >= 5.0 && < 6

library:
  source-dirs: src

executables:
  tip-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tip

tests:
  tip-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tip
